const status = {
  SUCCESS: 200,
  CREATED: 201,
  ERROR: 500,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  CONFLICT: 409,
  FORBIDDEN: 403,
  NOTFOUND: 404,
}

const MSG = {
  notFound: 'Not Found',
  notAuthorized: 'Path not authorized',
  dataNotFound: 'Data Not Found',
  somethingWentWrong: 'Something went wrong',
  alreadyExists: 'Already Exists',
  missingRequiredData: 'Missing required data',
  successfulLogin: 'Login successfully',
  notExists: 'Your account not Exists!',
  invalidCredentials: 'Invalid credentials',
  invalidId: 'Invalid ID',
  invalidEmail: 'Invalid E-mail',
  invalidMobileNo: 'Invalid Mobile no.',
  invalidData: 'Invalid data.',
  dataCreated: 'Data created',
  accountPending: 'Your Request is in pending state, please verify your account and try again',
  accountInActive: 'Your Request is in InActive state, kindly wait until Admin Activate your account',
  accountBlocked:
    'Your have entered wrong password too many times and your account is blocked, Reset your password to activate your account',
  unauthorizedAccess: 'The access is not autherized.',
  registeredSuccessfully: 'Registered successfully',
  addedSuccessfully: 'Added successfully',
  loginSuccessfully: 'Login successfully',
  foundSuccessfully: 'Data Found Successfully',
  updatedSuccessfully: 'Updated Successfully',
  uploadedSuccessfully: 'Uploaded Successfully',
  syncedSuccessfully: 'Synced Successfully',
  syncedFailed: 'Syncing Failed',
  deletedSuccessfully: 'Deleted Successfully',
  alreadyDeleted: 'Already deleted',
  invalidOTP: 'Invalid OTP',
  otpVerified: 'OTP verified',
  otpLimitExceeded: 'The OTP limit has been exceeded',
  otpSended: 'OTP sended',
  otpExpired: 'OTP expired',
  passwordUpdated: 'Password updated',
  accountNotActive: 'Your account is not active',
  usernameAlreadyUsed: 'Username is already used.',
  userExist: 'User data is already used.',
  accountActivated: 'Account activation completed.',
  accountAlreadyActive: 'Account is already Active.',
  alreadyVerified: 'Already active',
  alreadyUpdated: 'Already updated',
  alreadyBlocked: 'Already blocked',
  accountUnblocked: 'Account unblocked',
  verificationSuccess: 'Successfully verified.',
  packageNotExist: 'Package not exist',
  confirmPasswordNotMatchig: 'Confirm password is not matching.',
  cannotCancel: 'Cannot cancel this.',
  cannotUpdate: 'Cannot update this.',
  doctorNotAvailable: 'Doctor is not available this day',
  slotBooked: 'Slot booked successfully',
  dayIsNotWorking: 'This day is not working',
  twoAuthFactorsAreAlreadyExist: 'Two auth factors are already exist',
  loginAttemptExceeded: 'Login attempt exceeded the limit. Connect with authority for re-activate.',
}

module.exports = {
  status,
  MSG,
}
